kind: Service
apiVersion: v1
metadata:
  name: demokubernetesservice
spec:
  selector:
    app: demokubernetes
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 8080
      # Port to forward to inside the pod
      targetPort: 80
      # Port accessible outside cluster
      nodePort: 30002
  type: LoadBalancer



---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demokubernetes
spec:
  replicas: 5
  selector:
    matchLabels:
      app: demokubernetes
  template:
    metadata:
      labels:
        app: demokubernetes
    spec:
      containers:
        - name: demokubernetes
          image: shevchukstan/demokubernetes
          ports:
            - containerPort: 80